Weblog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('', include('account.urls')),
    path('articles/', include('blog.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

account/urls.py
from django.urls import path
from . import views

app_name = 'account'

# my urls


urlpatterns = [
    path('login/', views.log_in, name='login'),
    path('logout/', views.log_out, name='logout'),
    path('register/', views.register, name='register'),
    path('edit_profile/', views.edit_profile, name='edit_profile'),
    path('about_developer/', views.about_developer, name='about_developer'),
]

blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

# my urls


urlpatterns = [
    path('list', views.article_list, name='article_list'),
    path('detail/<slug:slug>', views.article_detail, name='article_detail'),
    path('category/<int:pk>', views.category_detail, name='category_detail'),
    path('search', views.search, name='article_search'),
    path('author/<int:pk>', views.author_detail, name='author_detail'),
    path('contact_us', views.contact_us, name='contact_us'),
    path('like/<slug:slug>/<int:pk>', views.like, name='like'),
    path('create_blog', views.create_blog, name='create_blog'),
]

home/urls.py
from django.urls import path
from . import views

app_name = 'home'

# my urls


urlpatterns = [
    path('', views.home, name='main'),
]

home/models.py
from django.db import models

# Create your models here.

home/views.py
from django.shortcuts import render
from blog import models


# Create your views here.

def home(request):
    articles = models.Article.objects.filter(status=True)
    recent_article = models.Article.objects.filter(status=True).order_by('-pub_date')[:3]
    return render(request, 'home/home.html', {'articles': articles, 'recent_article': recent_article})

home/templates/home/home.html
{% extends 'base/base.html' %}
{% load social_share %}
{% load simple_tags %}
{% load static %}



{% block title %}Home{% endblock %}
{% block content %}
    <!-- Banner Starts Here -->
    <div class="main-banner header-text">
        <div class="container-fluid">
            <div class="owl-banner owl-carousel">
                {% for article in recent_article %}
                    <div class="item">
                        <img src="{{ article.image.url }}" alt="{{ article.title }}">
                        <div class="item-content">
                            <div class="main-content">
                                <div class="meta-category">
                                    <span>{{ article.category.first.title }}</span>
                                </div>
                                <a href="{{ article.get_absolute_url }}"><h4>{{ article.title }}</h4></a>
                                <ul class="post-info">
                                    <li>
                                        <a href="{% url 'blog:author_detail' article.author.id %}">{{ article.author }}</a>
                                    </li>
                                    <li><a href="{{ article.get_absolute_url }}">{{ article.pub_date }}</a></li>
                                    <li><a href="{{ article.get_absolute_url }}#comments-section">
                                        {% if article.comments.count == 1 %}{{ article.comments.count }} Comment
                                            {% else %}{{ article.comments.count }} Comments{% endif %}</a></li>
                                    <li><a href="{{ article.get_absolute_url }}">
                                        {% if article.views  == 1 %}
                                            {{ article.views }} view
                                        {% else %}
                                            {{ article.views }} views
                                        {% endif %}
                                    </a></li>
                                </ul>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>
    <!-- Banner Ends Here -->

    {% include 'includes/user_card_bar.html' %}

    {% if not articles %}
        <div class="container vh-100 d-flex justify-content-center align-items-center">
            <div class="text-center p-5 shadow-lg rounded bg-light">
                <i class="fa fa-folder-open text-primary mb-3" style="font-size: 4rem;"></i>
                <h1 class="text-dark">Articles Not Found</h1>
                <p class="text-muted">Sorry, there are no articles to display at the moment.</p>
                {% if request.user.is_authenticated %}
                    <a href="{% url 'blog:create_blog' %}" class="btn btn-primary mt-3">Create Blog</a>
                {% else %}
                    <a href="{% url 'account:login' %}" class="btn btn-primary mt-3">Login To Create Blog</a>
                {% endif %}
            </div>
        </div>
    {% else %}


    <section class="blog-posts">
        <div class="container">
            <div class="row">
                <div class="col-lg-8">
                    <div class="all-blog-posts">
                        <div class="row">
                            {% for article in recent_article %}
                                <div class="col-lg-12">
                                    <div class="blog-post">
                                        <div class="blog-thumb">
                                            <img src="{{ article.image.url }}" alt="{{ article.title }}">
                                        </div>
                                        <div class="down-content">
                                            <span>{{ article.category.first.title }}</span>
                                            <a href="{{ article.get_absolute_url }}"><h4>{{ article.title }}</h4></a>
                                            <ul class="post-info">
                                                <li>
                                                    <a href="{% url 'blog:author_detail' article.author.id %}">{{ article.author }}</a>
                                                </li>
                                                <li><a href="{{ article.get_absolute_url }}">{{ article.pub_date }}</a></li>
                                                <li><a href="{{ article.get_absolute_url }}#comments-section">
                                                    {% if article.comments.count == 1 %}{{ article.comments.count }}
                                                        Comment
                                                        {% else %}{{ article.comments.count }} Comments{% endif %}</a>
                                                </li>
                                                <li><a href="{{ article.get_absolute_url }}">
                                                    {% if article.views  == 1 %}
                                                        {{ article.views }} view
                                                    {% else %}
                                                        {{ article.views }} views
                                                    {% endif %}
                                                </a></li>
                                            </ul>
                                            <p>{{ article.body|truncatewords:20 }}</p>
                                            <div class="post-options">
                                                <div class="row">
                                                    <div class="col-6">
                                                        {% if request.user.is_authenticated %}
                                                            <ul class="post-tags">
                                                                {% if article.id in liked_article_ids %}
                                                                    <li>
                                                                        <a onclick="like('{{ article.slug }}', '{{ article.id }}')">
                                                                            <i class="fa fa-heart" data-article-id="{{ article.id }}"></i>
                                                                        </a>
                                                                        <span class="like-count"
                                                                              data-article-id="{{ article.id }}">{{ article.likes.all.count }}</span>
                                                                    </li>
                                                                {% else %}
                                                                    <li>
                                                                        <a onclick="like('{{ article.slug }}', '{{ article.id }}')">
                                                                            <i class="fa fa-heart-o"
                                                                               data-article-id="{{ article.id }}"></i>
                                                                        </a>
                                                                        <span class="like-count"
                                                                              data-article-id="{{ article.id }}">{{ article.likes.all.count }}</span>
                                                                    </li>
                                                                {% endif %}
                                                            </ul>
                                                        {% else %}
                                                            <ul class="post-tags">
                                                                <li>
                                                                    <a href="{% url 'account:login' %}">
                                                                        <i id="like" class="fa fa-heart-o"></i>
                                                                    </a>{{ article.likes.count }}
                                                                </li>
                                                            </ul>
                                                        {% endif %}
                                                    </div>
                                                    <div class="col-6">
                                                        <ul class="post-share">
                                                            <li><i class="fa fa-share-alt"></i></li>
                                                            <li>{% post_to_whatsapp article.get_absolute_url "whatsApp" %}</li>
                                                            ,
                                                            <li>{% post_to_telegram 'The blog: {{ article.title }}. Click it out!' article.get_absolute_url "telegram" %}</li>
                                                        </ul>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            {% endfor %}
                            <div class="col-lg-12">
                                <div class="main-button">
                                    <a href="{% url 'blog:article_list' %}">View All Posts</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                {% include 'includes/side_bar.html' %}
            </div>
        </div>
    </section>
    {% endif %}
{% endblock %}