Weblog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('', include('account.urls')),
    path('articles/', include('blog.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

account/urls.py
from django.urls import path
from . import views

app_name = 'account'

# my urls


urlpatterns = [
    path('login/', views.log_in, name='login'),
    path('logout/', views.log_out, name='logout'),
    path('register/', views.register, name='register'),
    path('edit_profile/', views.edit_profile, name='edit_profile'),
    path('about_developer/', views.about_developer, name='about_developer'),
]

blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

# my urls


urlpatterns = [
    path('list', views.article_list, name='article_list'),
    path('detail/<slug:slug>', views.article_detail, name='article_detail'),
    path('category/<int:pk>', views.category_detail, name='category_detail'),
    path('search', views.search, name='article_search'),
    path('author/<int:pk>', views.author_detail, name='author_detail'),
    path('contact_us', views.contact_us, name='contact_us'),
    path('like/<slug:slug>/<int:pk>', views.like, name='like'),
    path('create_blog', views.create_blog, name='create_blog'),
]

home/urls.py
from django.urls import path
from . import views

app_name = 'home'

# my urls


urlpatterns = [
    path('', views.home, name='main'),
]

templates/includes/footer.html
{% load static %}
<footer>
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <ul class="social-icons">
                    <li><a href="{{ admin.linkedin }}" target="_blank">Linkedin</a></li>
                    <li><a href="{{ admin.github }}" target="_blank">Github</a></li>
                </ul>
            </div>
            <div class="col-lg-12">
                <div class="copyright-text">
                    <p>This site is owned by<a href="{% url 'account:about_developer' %}"> Parsa Sobbouhi</a>.</p>
                    <p>This site is developed by Parsa Sobbouhi using Django framework.</p>
                </div>
            </div>
        </div>
    </div>
</footer>

templates/includes/footer_references.html
{% load static %}
<!-- Bootstrap core JavaScript -->
<script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
<script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

<!-- Additional Scripts -->
<script src="{% static 'js/custom.js' %}"></script>
<script src="{% static 'js/owl.js' %}"></script>
<script src="{% static 'js/slick.js' %}"></script>
<script src="{% static 'js/isotope.js' %}"></script>
<script src="{% static 'js/accordions.js' %}"></script>
<script src="{% static 'js/ajax.js' %}"></script>


<script language="text/Javascript">
    cleared[0] = cleared[1] = cleared[2] = 0; //set a cleared flag for each field
    function clearField(t) {                   //declaring the array outside of the
        if (!cleared[t.id]) {                      // function makes it static and global
            cleared[t.id] = 1;  // you could use true and false, but that's more typing
            t.value = '';         // with more chance of typos
            t.style.color = '#fff';
        }
    }
</script>

templates/includes/header.html
{% load static %}
<!-- Header -->
<header>
    <nav class="navbar navbar-expand-lg">
        <div class="container">
            <a class="navbar-brand" href="{% url 'home:main' %}"><h2>Stand Blog<em>.</em></h2></a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive"
                    aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarResponsive">
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item {% if request.resolver_match.url_name == 'main' %} active {% endif %}">
                        <a class="nav-link" href="{% url 'home:main' %}">Home
                            <span class="sr-only">(current)</span>
                        </a>
                    </li>
                    <li class="nav-item {% if request.resolver_match.url_name == 'about_developer' %} active {% endif %}">
                        <a class="nav-link" href="{% url 'account:about_developer' %}">About Developer</a>
                    </li>
                    <li class="nav-item {% if request.resolver_match.url_name == 'article_list' %} active {% endif %}">
                        <a class="nav-link" href="{% url 'blog:article_list' %}">Blog Entries</a>
                    </li>
                    <li class="nav-item {% if request.resolver_match.url_name == 'contact_us' %} active {% endif %}">
                        <a class="nav-link" href="{% url 'blog:contact_us' %}">Contact Us</a>
                    </li>
                    <li class="nav-item {% if request.resolver_match.url_name == 'edit_profile' %} active {% endif %}">
                        {% if request.user.is_authenticated %}
                            {% if user.image %}
                                <span><img src="{{ user.image.url }}" alt="Profile Photo" width="25px"
                                           height="25px" style="border-radius: 100%"></span>
                            {% else %}
                                <span><img src="{% static 'images/user.png' %}" alt="Profile Photo" width="25px"
                                           height="25px" style="border-radius: 100%"></span>
                            {% endif %}
                            <a class="nav-link"
                               href="{% url 'account:edit_profile' %}">{{ request.user.first_name }}</a>

                        {% endif %}
                    </li>
                    <li class="nav-item {% if request.resolver_match.url_name == 'create_blog' %} active {% endif %}">
                        {% if request.user.is_authenticated %}
                            <a class="nav-link" href="{% url 'blog:create_blog' %}">Create blog</a>
                        {% endif %}
                    </li>
                    <li class="nav-item">
                        {% if request.user.is_authenticated %}
                            <a class="nav-link" href="{% url 'account:logout' %}">LOGOUT</a>
                        {% else %}
                            <a class="nav-link" href="{% url 'account:login' %}">LOGIN</a>
                        {% endif %}
                    </li>
                    <li>
                        {% if request.user.is_authenticated == False %}
                            <a class="nav-link" href="{% url 'account:register' %}">REGISTER</a>
                        {% endif %}
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</header>

<!-- Page Content -->

templates/includes/header_references.html
{% load static %}
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<meta name="description">
<meta name="author" content="TemplateMo">
<link href="https://fonts.googleapis.com/css?family=Roboto:100,100i,300,300i,400,400i,500,500i,700,700i,900,900i&display=swap"
      rel="stylesheet">

<title>Stand CSS Blog by TemplateMo</title>

<!-- Bootstrap core CSS -->
<link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">


<!-- Additional CSS Files -->
<link rel="stylesheet" href="{% static 'css/fontawesome.css' %}">
<link rel="stylesheet" href="{% static 'css/templatemo-stand-blog.css' %}">
<link rel="stylesheet" href="{% static 'css/owl.css' %}">

templates/includes/side_bar.html
{% load static %}
<div class="col-lg-4">
    <div class="sidebar">
        <div class="row">
            <div class="col-12 d-flex justify-content-center">
                <div class="sidebar-item search">
                    <form id="search_form" name="gs" method="GET" action="{% url 'blog:article_search' %}">
                        <div class="input-group">
                            <label>
                                <input type="text" name="search" class="form-control" placeholder="type to search..." autocomplete="on">
                            </label>
                            <button class="btn btn-primary" type="submit">
                                <i class="fa fa-search"></i>
                            </button>
                        </div>
                    </form>
                </div>
            </div>
            <div class="col-lg-12">
                <div class="sidebar-item recent-posts">
                    <div class="sidebar-heading">
                        <h2>Recent Posts</h2>
                    </div>
                    <div class="content">
                        <ul>
                            {% for article in recent_articles %}
                                <li><a href="{{ article.get_absolute_url }}">
                                    <h5>{{ article.title }}</h5>
                                    <span>{{ article.updated }}</span>
                                </a></li>
                            {% endfor %}
                        </ul>
                    </div>
                </div>
            </div>
            <div class="col-lg-12">
                <div class="sidebar-item categories">
                    <div class="sidebar-heading">
                        <h2>Categories</h2>
                    </div>
                    <div class="content">
                        <ul>
                            {% for category in categories %}
                                <li><a href="{{ category.get_absolute_url }}">- {{ category }}</a></li>
                            {% endfor %}
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

templates/includes/user_card_bar.html
{% load simple_tags %}
<section class="call-to-action">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="main-content">
                    <div class="row">
                        <div class="col-lg-8">
                            {% if request.user.is_authenticated %}
                                <span>Hello {{ request.user.get_full_name }}!</span>
                                <h4>{% current_time '%Y-%m-%d' %}</h4>
                            {% else %}
                                <span>Hello User!</span>
                                <h4>{% current_time '%Y-%m-%d' %}</h4>
                            {% endif %}
                        </div>
                        <div class="col-lg-4">
                            {% if request.user.is_authenticated %}
                                <div class="main-button">
                                    <a href="{% url 'blog:create_blog' %}">Create your blog</a>
                                </div>
                            {% else %}
                                <div class="main-button">
                                    <a href="{% url 'account:login' %}">Logging in to create your blog</a>
                                </div>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>